In [1]:
import numpy as np

In [4]:
#array.shape discern dimention and volume of your array
array1 = np.array([1,2,3])
print ('array1 type:' , type(array1))
print ('array1 array TYPE:' , array1.shape)

array2 = np.array([[1,2,3],
                 [2,3,4]])
print ('array2 type:' , type(array2))
print ('array2 array TYPE:' , array2.shape)

array3 = np.array([[1,2,3]])
print ('array3 type:' , type(array3))
print ('array3 array TYPE:' , array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array TYPE: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array TYPE: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array TYPE: (1, 3)


In [5]:
#to check dimention you uese ndarray.ndim
print('array1: {:0} Dimension, array2: {:1} Dimension, array3: {:2} Dimension'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1 Dimension, array2: 2 Dimension, array3:  2 Dimension


In [6]:
#Only having numberic narray
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
#Unlike list array has trobule calling all the types when having different types value include
list2 = [1,2,'test']
print(type(list2))
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11


In [8]:
#arange orderly assign numeric starting from 0
sequence_array = np.arange(10)
print (sequence_array)
print (sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [10]:
#fill in zeros
zero_array = np.zeros((3,4), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#fill in ones
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32 (3, 4)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [11]:
print(array1)
print(array1.shape)

[1 2 3]
(3,)


In [12]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 3 into shape (4,3)

In [13]:
array1 = np.arange(10)
print(array1)

#When we use -1 in either row or column it assigns number automatically
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [14]:
#Let's create array starting from 1 to 10
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)

#trying to call out 3rd col note that index starts from '0', array1[2] = 3rd one
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
# Using '-' we can pull out from the last
print('Back:', array1[-1],', Second Back:', array1[-2])

Back: 9 , Second Back: 8


In [16]:
#Easily replace and update
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [22]:
rand = np.random.RandomState(42)

x=rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [23]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [24]:
ind = [3,7,4]
x[ind]

array([71, 86, 60])

In [25]:
ind = np.array([[3,7], [4,5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [26]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
row = np.array([0,1,2])
col = np.array([2,1,3])
print(row)
print(col)
X[row, col]

[0 1 2]
[2 1 3]


array([ 2,  5, 11])

In [31]:
array1d = np.arange(start = 1, stop =10)

#inside the list [] ndrray1d > 5 Boolean indexing
array3 = array1d[array1d > 5]
print('array1d > Boolean Indexing Result :', array3)

array1d > Boolean Indexing Result : [6 7 8 9]


In [32]:
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [35]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print('Inverse matrix A:\n', transpose_mat)

Inverse matrix A:
 [[1 3]
 [2 4]]
